### PR TITLE
Functions

### PR DESCRIPTION
**Pull request by seankross**
There's still work to be done, but I wanted to give you a preview.

### CODE REVIEW

**Comment by seankross** [comment]
Well my comment above makes me look like a fool but I'm finally happy with this lesson. I'd appreciate if somebody could go through it before a merge. @ncarchedi

**Comment by ncarchedi** [comment]
@seankross Awesome, thanks! I don't have time to review just this second, but will try to take a look tonight or tomorrow. Would love to hear what everyone else thinks.

Just a reminder to everyone, don't merge any new lessons in our Coursera-based courses before I have had a chance to add them to the grading scheme on Coursera's servers. We learned this lesson the hard way a few weeks back :-)

**Comment by seankross** [comment]
Also just as a reminder, I'm ready for this to be merged.

**Comment by ncarchedi** [comment]
Cool, will run though it this week and hopefully merge before next month's Coursera session.

**Comment by ncarchedi** [comment]
This is my new favorite swirl lesson. I even learned a few new tricks!! Merging now and adding to the Coursera auto-grader.

**Comment by seankross** [comment]
:heart: :heart: :heart:

**Pull request merged**
