### PR TITLE
Added missing ggplot2 dependency to dependson.txt

### PR DESCRIPTION
**Pull request by NickUK**
To avoid this error in the Exploratory Data Analysis / Principles of Analytic Graphs course:
> Error in library(ggplot2) : there is no package called ‘ggplot2’

I have added in the missing dependency ggplot2 dependency.

### CODE REVIEW

**Comment by NickUK** [comment]
Added another missing dependency in the case study

**Comment by seankross** [comment]
What makes you believe that CaseStudy is dependent on `fields`?

**Comment by NickUK** [comment]
image

I couldn't get it to work without installing it

**Comment by seankross** [comment]
Thank you!

**Pull request merged**
