### PR TITLE
Solves the problem with ggplot2 Verison 2.0.0 or later

### PR DESCRIPTION
**Pull request by NormandDesmarais**
Solve the following error message with ggplot2 version 2.0.0 or later:

Error in layer("area", mapping = aes(x = ifelse(x > qnorm(0.95, sd = 2), :
unused argument (geom_params = list(fill = "red", alpha = 0.5))
| Leaving swirl now. Type swirl() to resume.

### CODE REVIEW

**Comment by weilu** [comment]
This is the right fix. Can someone merge this ASAP please? This fixes the error that's blocking people from completing their exercises this week.

**Comment by seankross** [comment]
@NormandDesmarais looks good. Thank you for this fix.

**Comment by ehre** [comment]
Great, thanks. Works like a charm.

**Comment by NormandDesmarais** [comment]
Cool!

**Pull request merged**
