### PR TITLE
Eda

### PR DESCRIPTION
**Pull request by reginaastri**
Don't merge this branch on Exploratory Data Analysis yet. It needs more beta testing. It works on my system (linux) but I'd like to see if it works on windows, mac, etc. Also, the last lesson (Case Study) might be slow to run since it involves some large data files. 

Thanks.

### CODE REVIEW

**Comment by reginaastri** [comment]
The course has been alpha tested and several problems have been fixed. I believe it's ready to merge.  I'll merge it Monday evening unless I hear to the contrary.

**Comment by ncarchedi** [comment]
@reginaastri Amazing, thanks! I'm going to be doing some R training at my office and will definitely encourage people to work through this course.

**Comment by reginaastri** [comment]
I'll probably merge this tomorrow (Tuesday). I found a few testing problems with it and I want to stress it a bit more before it's merged.

**Comment by seankross** [comment]
:fireworks: :beers: :tada: :confetti_ball: Such amazing work @reginaastri !

**Pull request merged**
