### PR TITLE
Adding two lessons to R_Programming

### PR DESCRIPTION
**Pull request by davidkane9**
This pull request adds two new lessons to R_Programming: Workspace_and_Files and Base_Graphics. I plan on creating more lessons like this. Both new lessons have been tested.  If there are guidelines I should be following with these lessons, please let me know. Advice on length and difficulty is also welcome.

If there are any recommendations for how to work with the repository, please let me know. As you can see, right now I am just working on master. That works fine, although it means that, if I add another lesson tomorrow, my next pull request (if this one has not already been processed) will include these lessons as well. (Corrections welcome.) If this is not desirable, please let me know. If it does no harm, then I am happy enough t work this way.

### CODE REVIEW

**Comment by WilCrofter** [comment]
Well done! I've gone through  both lessons and think they're terrific. I do have some technical comments--matters which a set of guidelines, had one existed, would have obviated I agree.  Except for these technicalities, the lessons should be merged, IMO. 

I would move Workspace and Files to an earlier position, perhaps position 2, in the manifest.

Since R Programming is for Coursera, the lesson Type, in the yaml header, should be Coursera rather than Standard. Type Coursera triggers an completion reporting sequence at the end of every lesson. R Programming Alt, is identical to R Programming except that lessons are marked Standard. 

Base Graphics repeats every plot the user creates. This can be avoided by including a customTests.R file in the lesson subdirectory with the line `AUTO_DETECT_NEWVAR <- FALSE`. When this flag is `FALSE`, testing for new variables must be done question by question using `creates_new_var`. No new variables are created in Base Graphics, but I mention it because the feature is undocumented. I hesitate to document it before a code review and plan to make things easier for course authors with a well thought out API.

### Workspace and Files
* "Remove x from the workspace." Unfortunately, the CRAN version of swirl still has the `rm` bug. The fix is in the development version which won't reach CRAN for several months. (There are restrictions on how often we can update the swirl core at CRAN. Swirl courses, in contrast, are updated instantly at github.) 
*  "List all the files in your working directory." There are several ways to do this, e.g. `dir()`, and someone will surely complain that their favorite is not acceptable. (I think this is our most frequent complaint.) Use `any_of_exprs` rather than `omnitest`?
*  "Pull up the help for list.files()". Same as above: `help("list.files")` etc.
* "Access information about "my.test.R"."  Should read "mytest.R" not "my.test.R".

### Base Graphics
* "Use plot() command to show speed on the x-axis..." There are other ways to do this, e.g., `plot( dist ~ speed, cars)`. Omnitest will take care of some of this, but won't reconcile  `plot(x, y)` and `plot(y ~ x)` forms.
* "Use plot() command to show dist on the x-axis..." Same.

**Comment by davidkane9** [comment]
Thanks for these suggestions. The below have been implemented.

[x] I would move Workspace and Files to an earlier position, perhaps position 2, in the manifest.
[x]  the lesson Type, in the yaml header, should be Coursera rather than Standard.
[x] "Remove x from the workspace."  --- Removed these questions.
[x] " Should read "mytest.R" not "my.test.R".
[x] "List all the files in your working directory."
[x] Pull up the help for list.files()"

I did not know what to do about this one.

[] Base Graphics repeats every plot the user creates.

I am nervous about using undocumented tricks. Also, seems like the current behavior does no harm.

Also, I am conflicted about your comments here:
 
[] "Use plot() command to show speed on the x-axis..." There are other ways to do this, e.g., plot( dist ~ speed, cars).

I agree that there are other ways to do this. But the goal of this intro lesson is not to show those other ways. (Or, at least not to show them in the first few commands.) Instead, the goal is just to get some simple plots working and then show some of the different arguments that one can use.

So, I made the instructions for that question more explicit and also had an explanation about the formula interface.

Thanks for the suggestions!

**Comment by WilCrofter** [comment]
> Re: I am nervous about using undocumented tricks. Also, seems like the current behavior does no harm. 

I understand. So am I. For one thing, revisions of the core code will probably require undoing these tricks later. BTW, there is another undocumented trick to restore plots when a user quits a lesson partway through and resumes at a later date. At the moment this won't happen, but the lesson is short and plots are more or less independent anyway.

> Re: I made the instructions for that question more explicit and also had an explanation about the formula interface.

That should work. Similar things are done in other lessons and they seem to make users happy.

Following Nick's nod in his Recap/Priorities post, I'll wait a few hours for comment, then merge.

**Comment by davidkane9** [comment]
> I'll wait a few hours for comment, then merge.

Cool! This makes it easier for me to use the lesson in my class starting on Monday. Much appreciated. 

I just went through the two new lessons one more time, cleaning up some of the text and expanding the set of allowed answers.

**Pull request merged**
