### PR TITLE
Update lesson.yaml

### PR DESCRIPTION
**Pull request by cimentadaj**

### CODE REVIEW

**Comment by seankross** [comment]
Thanks!

**Comment by cimentadaj** [comment]
Hi Sean,

There's also a problem in the swirl lesson on residuals in the Regression Modeling course. I can't seem to figure out what the problem is but one can not advance after the question in line 84 [here](https://github.com/swirldev/swirl_courses/blob/master/Regression_Models/Residuals/lesson.yaml).

There seems to be a problem when calling line 86. Let me know if I should open this in a thread in the residual section.

**Comment by seankross** [comment]
@cimentadaj I can't reproduce the error. What error are you encountering?

**Comment by cimentadaj** [comment]
@seankross It happened on an old Windows Microsoft Windows XP. When I retried doing it in a MacBook Pro it worked fine. The R version is 3.2.4.

**Comment by seankross** [comment]
Good to know, thanks.

**Pull request merged**
